### ISSUE TITLE
Unable to load CSS rules

### ISSUE THREAD

**Issue by FatiMooni** [ArtyomVancyan/antd-phone-input#31]
I am occasionally getting the below errors when using `<PhoneInput />`  component 

error : 
<img width="734" alt="Screenshot 2023-04-25 at 12 43 28 PM" src="https://user-images.githubusercontent.com/32798333/234266505-4dd458cc-fe2a-48eb-a7b2-8e70f44b4aaf.png">

dependencies : 

antd-phone-input: "^0.1.4"
antd : "^5.4.2"
react: "^18.2.0"
react-dom: "^18.2.0"

any idea why I am getting this ?

**Comment by FatiMooni** [comment]
Hi @ArtyomVancyan , the bug appears occasionally , I couldn't find the exact steps to reproduce.

Here's how I am using it 
```
// other importants
import PhoneInput from 'antd-phone-input';

// some code 

// component
  return (
       <Form layout="vertical" form={form}>
        
        <Form.Item
          label="Phone number"
          name={'mobileNumber'}
          rules={[
            {
              required: true,
              message: 'Please enter your Phone Number!',
            },
            () => ({
              validator(rule, value) {
                if (value && value.valid) {
                  return Promise.resolve();
                }

                return Promise.reject(
                  'The inserted phone number  is not valid !'
                );
              },
            }),
          ]}
        >
          <PhoneInput enableSearch />
        </Form.Item>
      // rest of code
      </Form>
     
  );
};

```

**browser** : Chrome

**Comment by ArtyomVancyan** [comment]
Hey @FatiMooni, thanks for providing your code. All you do is right. I just noticed that it happens occasionally. So I have fixed the only possible cause of that error. Please upgrade the `antd-phone-input` version to `0.1.5` and check again. Please verify that the error has gone.
