### ISSUE TITLE
CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet

### ISSUE THREAD

**Issue by g-vellis-se** [ArtyomVancyan/antd-phone-input#35]
### Bug description

I have installed antd-phone-input in a clean vite project (vite v.4.3.2) using ant design v.5.5.2 (i.e. the latest version), but I keep getting an error when accessing the page with the phone-input-component via Firefox (v. 114.0 64-bit, i.e. the latest). 

Notably, it works fine in all other browsers I have tested it (Chrome and Safari).

To use the <PhoneInput> component, I used the following code (as suggested in the documention):

import FormItem from "antd/es/form/FormItem";
import PhoneInput from "antd-phone-input";

<img width="294" alt="image" src="https://github.com/ArtyomVancyan/antd-phone-input/assets/131464434/87458ced-907c-4a66-853b-9e243f4e465d">

The image below, shows the error I keep getting:
<img width="731" alt="image" src="https://github.com/ArtyomVancyan/antd-phone-input/assets/131464434/6e3fb15c-0f73-462d-8142-68440af6f19b">

Any ideas?
Thanks

### Reproduction steps

1. Create a vite project (npm create vite using React and TypeScript)
2. Install ther latest version of ant design (npm i antd)
3. Go into any .tsx file (e.g. App.tsx) and 
    3.1 Introduce the following three import statements: import FormItem from "antd/es/form/FormItem"; import PhoneInput from "antd-phone-input"; import {Form} from "antd";
    3.2 Try to use the PhoneInput component, i.e. 
<img width="290" alt="image" src="https://github.com/ArtyomVancyan/antd-phone-input/assets/131464434/371625c4-7035-4233-bf9f-c0083dec6ba0">

4. Navigate to the page which the PhoneInput component was added in, using Firefox. 

### Screenshots

<img width="741" alt="image" src="https://github.com/ArtyomVancyan/antd-phone-input/assets/131464434/04c744ca-dec5-4259-8587-cb00b354673b">

### Browsers

Firefox

### OS

Mac

**Comment by ArtyomVancyan** [comment]
Hi @g-vellis-se, thanks for reporting the issue. I have passed the reproduction steps but could not get the error you are facing with. As we can see in the error message, it is correlated with React Router. Could you please try to reproduce the issue on one of the following platforms if it is not open source:
 - https://codesandbox.io
 - https://stackblitz.com
 - https://codepen.io
 
My environment and dependencies
 - Node - v19.9.0
 - npm - 9.6.3
 
 ```json
 "dependencies": {
    "antd": "^5.6.1",
    "antd-phone-input": "^0.1.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
}
 ```

**Comment by g-vellis-se** [comment]
Hi @ArtyomVancyan ,

Thank you very much for the prompt reply.

The issue was caused by the following Firefox plugin: "Adjust Screen Brightness" (see: https://addons.mozilla.org/en-US/firefox/addon/adjust-screen-brightness/). Once I disabled it, everything worked as expected.

**Comment by vishwajit76** [comment]
same issue

**Comment by ArtyomVancyan** [comment]
@vishwajit76, please share some code snippets. Try to disable browser add-ons one by one to find the possible cause.
