### ISSUE TITLE
🐛 Bug Report - Mozambique Digits

### ISSUE THREAD

**Issue by Elson-Timana** [ArtyomVancyan/antd-phone-input#45]
### Bug description

The Mozambique, only accept 8 digits while need to accept 9

### Reproduction URL

https://github.com/Elson-Timana

### Screenshots

![DESCRIPTION](LINK.png)

**Comment by ArtyomVancyan** [comment]
The has been already fixed, make sure you are using the latest version.

**Comment by Elson-Timana** [comment]
Thanks
